image: python:3.9-alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POSTGRES_HOST_AUTH_METHOD: "trust"

services:
  - postgres:alpine

cache:
  paths:
    - .cache/pip

tests:
  before_script:
    - python -V
    - time apk --update add --no-cache build-base gcc libgcc libffi-dev openssl-dev git postgresql-client jpeg-dev openjpeg-dev zlib-dev freetype-dev lcms2-dev freetype-dev gifsicle
    - time pip3 install poetry wheel tox
    - time poetry install
  script:
    - ls
    - cp config.ci.py config.py
    - time tox
