image: python:3.7-alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

services:
  - postgres:alpine

cache:
  paths:
    - .cache/pip

tests:
  before_script:
    - python -V
    - apk --update add --no-cache build-base gcc libgcc libffi-dev openssl-dev git postgresql-client jpeg-dev openjpeg-dev zlib-dev freetype-dev lcms2-dev freetype-dev
    - pip3 install pipenv wheel tox
    - pipenv install --dev
  script:
    - ls
    - cp config.ci.py config.py
    - psql -h postgres -U postgres -f schema.sql
    - pipenv run ./manage.py migrate
    - pipenv run ./manage.py setup_tests
    - tox
